### ISSUE TITLE
Test & Verify developers site deploy

### ISSUE THREAD

**Issue by jf990** [jf990/project-management#14]
## Task:
Test the deploy process make sure it works. Verify all files that should copy are, and that should not are not. Develop/document  a way to test this when changes are made.

site deployment whitelist 
https://github.com/ArcGIS/arcgis-for-developers/blob/master/contrib/directory_copy_whitelist.txt

From Kevin:
I use the following command on Jenkins when using the whitelist.
```
rsync -av --delete --delete-excluded --include-from 'whitelist.txt' /source/developers/ /dest/developers/
```

## Todo:
 - [ ] Set up VM at https://red-inf-vra-p01.esri.com/vcac/#
 - [ ] Install node 6
 - [ ] Install arcgis-for-developers, cd
 - [ ] connect to `\\CORE\Developers` as `/source/develoeprs`
 - [ ] build site, make sure everything works
 - [ ] mkdir scratch destination folder as `/dest/developers`
 - [ ] run rsync (see above)
 - [ ] `grunt deploy --out=/dest/developers`

**Comment by jf990** [comment]
based on whitelist developments we no longer need to do this.
